export const mockProviders = [
  {
    id: 1,
    username: "eternalrest",
    email: "contact@eternalrest.ph",
    password: "",
    fullName: "Eternal Rest Funeral Services",
    userType: "provider",
    profileComplete: true,
    createdAt: new Date(),
    businessName: "Eternal Rest Funeral Services",
    location: "Bacoor, Cavite",
    rating: 4.9,
    reviewCount: 156,
    bookingCount: 235,
    priceRange: {
      min: 1500000,
      max: 3500000,
    },
    allowsCustomCasket: true,
    hasFlowerOptions: true,
    hasMemorialRoom: true,
    profileBio:
      "Serving families with compassion and dignity for over 25 years. We offer comprehensive funeral services with customizable options to honor your loved ones.",
  },
  {
    id: 2,
    username: "serenepassage",
    email: "care@serenepassage.ph",
    password: "",
    fullName: "Serene Passage Memorial",
    userType: "provider",
    profileComplete: true,
    createdAt: new Date(),
    businessName: "Serene Passage Memorial",
    location: "Dasmariñas, Cavite",
    rating: 4.7,
    reviewCount: 98,
    bookingCount: 187,
    priceRange: {
      min: 1200000,
      max: 2800000,
    },
    allowsCustomCasket: true,
    hasFlowerOptions: true,
    hasMemorialRoom: false,
    profileBio:
      "Providing respectful funeral arrangements with a focus on personalized services and eco-friendly options. Our compassionate team helps you create meaningful memorials.",
  },
  {
    id: 3,
    username: "gracefuljourney",
    email: "support@gracefuljourney.ph",
    password: "",
    fullName: "Graceful Journey Funerals",
    userType: "provider",
    profileComplete: true,
    createdAt: new Date(),
    businessName: "Graceful Journey Funerals",
    location: "Imus, Cavite",
    rating: 4.8,
    reviewCount: 124,
    bookingCount: 210,
    priceRange: {
      min: 1800000,
      max: 4000000,
    },
    allowsCustomCasket: false,
    hasFlowerOptions: true,
    hasMemorialRoom: true,
    profileBio:
      "A modern approach to funeral services, combining traditional respect with contemporary memorialization options. We offer beautiful venues and exceptional customer service.",
  },
  {
    id: 4,
    username: "peacefulrepose",
    email: "info@peacefulrepose.ph",
    password: "",
    fullName: "Peaceful Repose Services",
    userType: "provider",
    profileComplete: true,
    createdAt: new Date(),
    businessName: "Peaceful Repose Services",
    location: "General Trias, Cavite",
    rating: 4.6,
    reviewCount: 87,
    bookingCount: 165,
    priceRange: {
      min: 1000000,
      max: 2500000,
    },
    allowsCustomCasket: true,
    hasFlowerOptions: false,
    hasMemorialRoom: false,
    profileBio:
      "Affordable and dignified funeral services with a focus on casket customization. We help families create meaningful farewells without financial burden.",
  },
  {
    id: 5,
    username: "heavensgate",
    email: "service@heavensgate.ph",
    password: "",
    fullName: "Heaven's Gate Memorial",
    userType: "provider",
    profileComplete: true,
    createdAt: new Date(),
    businessName: "Heaven's Gate Memorial",
    location: "Tagaytay, Cavite",
    rating: 4.9,
    reviewCount: 143,
    bookingCount: 245,
    priceRange: {
      min: 2000000,
      max: 5000000,
    },
    allowsCustomCasket: true,
    hasFlowerOptions: true,
    hasMemorialRoom: true,
    profileBio:
      "Premium funeral services with scenic memorial spaces in Tagaytay. Our luxurious facilities and attentive staff ensure a perfect tribute to your loved ones.",
  },
  {
    id: 6,
    username: "sacredmemories",
    email: "help@sacredmemories.ph",
    password: "",
    fullName: "Sacred Memories Funeral Home",
    userType: "provider",
    profileComplete: true,
    createdAt: new Date(),
    businessName: "Sacred Memories Funeral Home",
    location: "Silang, Cavite",
    rating: 4.5,
    reviewCount: 76,
    bookingCount: 142,
    priceRange: {
      min: 1300000,
      max: 2700000,
    },
    allowsCustomCasket: false,
    hasFlowerOptions: true,
    hasMemorialRoom: true,
    profileBio:
      "Traditional funeral services with a focus on religious and cultural practices. We respect diverse traditions and provide specialized ceremonies for all faiths.",
  },
  {
    id: 7,
    username: "sacredmemories",
    email: "help@sacredmemories.ph",
    password: "",
    fullName: "Premium Memories Funeral Home",
    userType: "provider",
    profileComplete: true,
    createdAt: new Date(),
    businessName: "Sacred Memories Funeral Home",
    location: "Silang, Cavite",
    rating: 4.5,
    reviewCount: 76,
    bookingCount: 142,
    priceRange: {
      min: 7000000,
      max: 1000000,
    },
    allowsCustomCasket: false,
    hasFlowerOptions: true,
    hasMemorialRoom: true,
    profileBio:
      "Traditional funeral services with a focus on religious and cultural practices. We respect diverse traditions and provide specialized ceremonies for all faiths.",
  },
  {
    id: 8,
    username: "sacredmemories",
    email: "help@sacredmemories.ph",
    password: "",
    fullName: "Uniqe Memories Funeral Home",
    userType: "provider",
    profileComplete: true,
    createdAt: new Date(),
    businessName: "Sacred Memories Funeral Home",
    location: "Silang, Cavite",
    rating: 4.5,
    reviewCount: 76,
    bookingCount: 142,
    priceRange: {
      min: 2500000,
      max: 5000000,
    },
    allowsCustomCasket: false,
    hasFlowerOptions: true,
    hasMemorialRoom: true,
    profileBio:
      "Traditional funeral services with a focus on religious and cultural practices. We respect diverse traditions and provide specialized ceremonies for all faiths.",
  },
];
